### ISSUE TITLE
UI Refactor Plan and Task List

### ISSUE THREAD

**Issue by SuniRein** [SuniRein/yt-dlp-web#2]
To improve the user interface experience and usability, I plan to refactor the current UI. The main objectives are to optimize interaction patterns, enhance visual consistency, and improve input validation. Some of the listed features may not be implemented, as progress will be adjusted based on priorities.

- [x] Input validation #3 
  - [x] Add required field indicator (`*` after `label`)
  - [x] Real-time validation for user input
  - [x] Auto focus on the first invalid input field when summited
- [x] Hover-to-show description text #3
- [ ] Header navigation bar
  - [x] Header bar display #4 
  - [ ] Logo refine
  - [x] Page navigation #7 
  - [x] Display mode switch #5 
  - [ ] Language switch
- [x] Floating interactive button #6 
- [ ] Dynamically addable and removable option items
- [x] Log and preview display on a separate page #7 
- [x] Developer tools #9 
- [ ] Detailed and highly customized preview page
  - [x] A more elegant media info card #10 
- [ ] Download progress view
- [ ] Display a loading icon for actions in progress

**Comment by SuniRein** [comment]
I think the current changes is sufficient for this branch. The remained tasks may be implemented in the future, which will involve the backend and need more work.
